# Generated by Django 2.1.3 on 2018-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_temperaturereading_collected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='boilerTemperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='collectorsTemperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
