# Generated by Django 2.1.3 on 2018-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_auto_20181106_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectorsTemperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('boilerTemperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TemperatureReading',
        ),
    ]
